name: Build-Test-Publish Nuget with .NET Core

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish To NuGet Aev.MoqForLogs
        uses: brandedoutcast/publish-nuget@v2.5.4
        with:
          PROJECT_FILE_PATH: ./src/moq4logs/aev.moqforlogs.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: Aev.MoqForLogs
          INCLUDE_SYMBOLS: false
          # VERSION_REGEX: <Version>(.*)<\/Version>
          TAG_FORMAT: v*
