name: Moq For Logs Continuous Integration

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET 5 App
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
